export const municipalities = {
  "1st District": [
    "Guimbal",
    "Igbaras",
    "Miagao",
    "Oton",
    "San Joaquin",
    "Tigbauan",
    "Tubungan",
  ],
  "2nd District": [
    "Alimodian",
    "Leganes",
    "Leon",
    "New Lucena",
    "Pavia",
    "San Miguel",
    "Santa Barbara",
    "Zarraga",
  ],
  "3rd District": [
    "Badiangan",
    "Bingawan",
    "Cabatuan",
    "Calinog",
    "Janiuay",
    "Lambunao",
    "Maasin",
    "Mina",
    "Pototan",
  ],
  "4th District": [
    "Anilao",
    "Banate",
    "Barotac Nuevo",
    "Dingle",
    "Dueñas",
    "Dumangas",
    "Passi City",
    "San Enrique",
  ],
  "5th District": [
    "Ajuy",
    "Balasan",
    "Barotac Viejo",
    "Batad",
    "Carles",
    "Concepcion",
    "Estancia",
    "Lemery",
    "San Dionisio",
    "San Rafael",
    "Sara",
  ],
  "Iloilo City": [
    "Arevalo",
    "Iloilo City",
    "Jaro",
    "La Paz",
    "Lapuz",
    "Mandurriao",
    "Molo",
  ],
};
