export const sectors = [
  "All",
  "Bamboo",
  "Coffee & Cacao",
  "Coconut",
  "Processed Foods",
  "Coco",
  "Weaving",
  "IT - BPM",
];

export const municipalities = [
  "Ajuy",
  "Alimodian",
  "Anilao",
  "Badiangan",
  "Balasan",
  "Banate",
  "Barotac Nuevo",
  "Barotac Viejo",
  "Batad",
  "Bingawan",
  "Cabatuan",
  "Calinog",
  "Carles",
  "Concepcion",
  "Dingle",
  "Duenas",
  "Dumangas",
  "Estancia",
  "Guimbal",
  "Igbaras",
];

export const msmeLines = [
  {
    id: 1,
    name: "Miagao Farmers Agriculture Coop (MFAC)",
    category: "Coco",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Marjorie Paciosani",
    address: "Kirayan Tacas, Miagao",
    contactNumber: "0956-479-9139",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 2,
    name: "Net’s VCO",
    category: "Coco",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Nenita Desamero",
    address: "Poblacion, Lemery",
    contactNumber: "0910-850-2913",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 3,
    name: "New Lucena Coconut Agriculture Cooperative",
    category: "Coco",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Romeo Martino",
    address: "Cagban, New Lucena, Iloilo",
    contactNumber: "0945-476-1265",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 4,
    name: "San Dionisio Iloilo Herbal Growers Economic Enterprise Association (SANDIHGEEA)",
    category: "Coco",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Lea Canto",
    address: "Bondulan, San Dionisio, Iloilo",
    contactNumber: "0930-650-1148",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 5,
    name: "San Dionisio Multi Sectoral Integrated Association (SDMSIA)",
    category: "Coco",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Purification Benedicto",
    address: "Pase, San Dionisio",
    contactNumber: "0930-788-3043",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 6,
    name: "Spinner's Herbal & Wellness Enterprise",
    category: "Coco",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Ligaya N. Spinner",
    address: "Calampitao, Miagao, Iloilo",
    contactNumber: "0917-357-3853",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 7,
    name: "Teray’s Virgin Coconut Oil",
    category: "Coco",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Teresita Tulanda",
    address: "Nagba, Tigbauan",
    contactNumber: "0948-745-4371",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 8,
    name: "Tubungan Coconut Industry Development Project (CIDP)",
    category: "Coco",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Orlando Tacsagon",
    address: "San Jose, Tubungan",
    contactNumber: "0951-214-2767",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 9,
    name: "CM Bamboo Craft",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Sr. Angela Grijaldo, CM",
    address: "La Paz, Iloilo City",
    contactNumber: "0949-962-7174",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 10,
    name: "Creatif Products and Services Corp.",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Glenda E. Dagdag",
    address: "M.H. Del Pilar, Jaro, Iloilo City",
    contactNumber: "0907-383-6912",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 11,
    name: "UP Visayas Community-Based Bamboo Enterprise",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Ramer P. Bautista",
    address: "UPV Miagao Campus, Miagao, Iloilo",
    contactNumber: "0955-073-7319",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 12,
    name: "Skye Furniture Shop",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Generoso Laveros",
    address: "Nanga, Guimbal, Iloilo",
    contactNumber: "0975-710-2268",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 13,
    name: "Segundo's Bamboo Woven Products",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Segundo G. Esmeres",
    address: "Dakong, Guimbal, Iloilo",
    contactNumber: "0926-382-7208",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 14,
    name: "Leah's Bamboo Rattan Furniture",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Percy G. Garferio",
    address: "Nalundan, Guimbal, Iloilo",
    contactNumber: "0955-575-1200",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 15,
    name: "Lenskie Bamboo Products Manufacturing",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Helen T. Triste",
    address: "San Rafael, Tigbauan, Iloilo",
    contactNumber: "0948-578-0920",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 16,
    name: "Cabagua Bamboo Products Manufacturing",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Joueleen T. Cabagua",
    address: "Nagba, Tigbauan, Iloilo",
    contactNumber: "0926-104-5903",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 17,
    name: "Estember Bamboo Handicrafts Manufacturing",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Estelita T. Estember",
    address: "San Rafael, Tigbauan, Iloilo",
    contactNumber: "0999-923-5981",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
];
