export const sectors = [
  "All",
  "Bamboo",
  "Coffee",
  "Cacao",
  "Coconut",
  "Processed Foods",
  "IT - BPM",
  "Wearables and Homestyles",
];

export const municipalities = [
  "Ajuy",
  "Alimodian",
  "Anilao",
  "Badiangan",
  "Balasan",
  "Banate",
  "Barotac Nuevo",
  "Barotac Viejo",
  "Batad",
  "Bingawan",
  "Cabatuan",
  "Calinog",
  "Carles",
  "Concepcion",
  "Dingle",
  "Duenas",
  "Dumangas",
  "Estancia",
  "Guimbal",
  "Igbaras",
];

export const msmeLines = [
  {
    id: 1,
    name: "Miagao Farmers Agriculture Coop (MFAC)",
    category: "Coconut",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Marjorie Paciosani",
    address: "Kirayan Tacas, Miagao",
    contactNumber: "0956-479-9139",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 2,
    name: "Net’s VCO",
    category: "Coconut",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Nenita Desamero",
    address: "Poblacion, Lemery",
    contactNumber: "0910-850-2913",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 3,
    name: "New Lucena Coconut Agriculture Cooperative",
    category: "Coconut",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Romeo Martino",
    address: "Cagban, New Lucena, Iloilo",
    contactNumber: "0945-476-1265",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 4,
    name: "San Dionisio Iloilo Herbal Growers Economic Enterprise Association (SANDIHGEEA)",
    category: "Coconut",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Lea Canto",
    address: "Bondulan, San Dionisio, Iloilo",
    contactNumber: "0930-650-1148",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 5,
    name: "San Dionisio Multi Sectoral Integrated Association (SDMSIA)",
    category: "Coconut",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Purification Benedicto",
    address: "Pase, San Dionisio",
    contactNumber: "0930-788-3043",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 6,
    name: "Spinner's Herbal & Wellness Enterprise",
    category: "Coconut",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Ligaya N. Spinner",
    address: "Calampitao, Miagao, Iloilo",
    contactNumber: "0917-357-3853",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 7,
    name: "Teray’s Virgin Coconut Oil",
    category: "Coconut",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Teresita Tulanda",
    address: "Nagba, Tigbauan",
    contactNumber: "0948-745-4371",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 8,
    name: "Tubungan Coconut Industry Development Project (CIDP)",
    category: "Coconut",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Orlando Tacsagon",
    address: "San Jose, Tubungan",
    contactNumber: "0951-214-2767",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 9,
    name: "CM Bamboo Craft",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Sr. Angela Grijaldo, CM",
    address: "La Paz, Iloilo City",
    contactNumber: "0949-962-7174",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 10,
    name: "Creatif Products and Services Corp.",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Glenda E. Dagdag",
    address: "M.H. Del Pilar, Jaro, Iloilo City",
    contactNumber: "0907-383-6912",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 11,
    name: "UP Visayas Community-Based Bamboo Enterprise",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Ramer P. Bautista",
    address: "UPV Miagao Campus, Miagao, Iloilo",
    contactNumber: "0955-073-7319",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 12,
    name: "Skye Furniture Shop",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Generoso Laveros",
    address: "Nanga, Guimbal, Iloilo",
    contactNumber: "0975-710-2268",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 13,
    name: "Segundo's Bamboo Woven Products",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Segundo G. Esmeres",
    address: "Dakong, Guimbal, Iloilo",
    contactNumber: "0926-382-7208",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 14,
    name: "Leah's Bamboo Rattan Furniture",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Percy G. Garferio",
    address: "Nalundan, Guimbal, Iloilo",
    contactNumber: "0955-575-1200",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 15,
    name: "Lenskie Bamboo Products Manufacturing",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Helen T. Triste",
    address: "San Rafael, Tigbauan, Iloilo",
    contactNumber: "0948-578-0920",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 16,
    name: "Cabagua Bamboo Products Manufacturing",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Joueleen T. Cabagua",
    address: "Nagba, Tigbauan, Iloilo",
    contactNumber: "0926-104-5903",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 17,
    name: "Estember Bamboo Handicrafts Manufacturing",
    category: "Bamboo",
    description:
      "Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea Deserunt anim cupidatat nisi officia exercitation nostrud ea.",
    contactPerson: "Estelita T. Estember",
    address: "San Rafael, Tigbauan, Iloilo",
    contactNumber: "0999-923-5981",
    productGallery: [
      "/bamboo.jpg",
      "/coconut.png",
      "/coffee_and_cacao.jpg",
      "/processed_foods.jpg",
      "/it-bpm.jpg",
      "/weaving.png",
    ],
    majorProductLines: [],
  },
  {
    id: 18,
    name: "Iloilo Coffee Growers Association",
    category: "Coffee",
    description:
      "Leading coffee producer in Iloilo, specializing in Arabica and Robusta coffee beans with sustainable farming practices.",
    contactPerson: "Maria Santos",
    address: "Brgy. Poblacion, Leon, Iloilo",
    contactNumber: "0917-555-1234",
    productGallery: ["/coffee_and_cacao.jpg"],
    majorProductLines: [],
  },
  {
    id: 19,
    name: "Mountain Brew Coffee Co.",
    category: "Coffee",
    description:
      "Artisanal coffee roaster producing premium single-origin coffee from local beans.",
    contactPerson: "Juan dela Cruz",
    address: "Brgy. San Miguel, Alimodian, Iloilo",
    contactNumber: "0918-555-5678",
    productGallery: ["/coffee_and_cacao.jpg"],
    majorProductLines: [],
  },
  {
    id: 20,
    name: "Highlands Coffee Farm",
    category: "Coffee",
    description:
      "Family-owned coffee farm producing organic coffee and offering farm tours.",
    contactPerson: "Pedro Reyes",
    address: "Brgy. Bagumbayan, Janiuay, Iloilo",
    contactNumber: "0919-555-9012",
    productGallery: ["/coffee_and_cacao.jpg"],
    majorProductLines: [],
  },
  {
    id: 21,
    name: "Green Bean Coffee Roasters",
    category: "Coffee",
    description:
      "Specialty coffee roaster focusing on sustainable sourcing and artisanal roasting techniques.",
    contactPerson: "Ana Lim",
    address: "Brgy. Santo Niño, Tubungan, Iloilo",
    contactNumber: "0920-555-3456",
    productGallery: ["/coffee_and_cacao.jpg"],
    majorProductLines: [],
  },
  {
    id: 22,
    name: "Coffee Heritage Farm",
    category: "Coffee",
    description:
      "Traditional coffee farm preserving local coffee varieties and processing methods.",
    contactPerson: "Ricardo Garcia",
    address: "Brgy. San Jose, Leon, Iloilo",
    contactNumber: "0921-555-7890",
    productGallery: ["/coffee_and_cacao.jpg"],
    majorProductLines: [],
  },
  {
    id: 23,
    name: "Iloilo Cacao Farmers Cooperative",
    category: "Cacao",
    description:
      "Cooperative of cacao farmers producing high-quality cacao beans and artisanal chocolate.",
    contactPerson: "Manuel Cruz",
    address: "Brgy. Santa Cruz, Lambunao, Iloilo",
    contactNumber: "0922-555-1234",
    productGallery: ["/coffee_and_cacao.jpg"],
    majorProductLines: [],
  },
  {
    id: 24,
    name: "Tablea Chocolate House",
    category: "Cacao",
    description:
      "Traditional tablea maker using local cacao beans for authentic Filipino chocolate drinks.",
    contactPerson: "Carmen Flores",
    address: "Brgy. Poblacion, Calinog, Iloilo",
    contactNumber: "0923-555-5678",
    productGallery: ["/coffee_and_cacao.jpg"],
    majorProductLines: [],
  },
  {
    id: 25,
    name: "Cacao Valley Farm",
    category: "Cacao",
    description:
      "Integrated cacao farm producing beans, chocolate products, and offering agritourism.",
    contactPerson: "Roberto Torres",
    address: "Brgy. San Antonio, Leon, Iloilo",
    contactNumber: "0924-555-9012",
    productGallery: ["/coffee_and_cacao.jpg"],
    majorProductLines: [],
  },
  {
    id: 26,
    name: "Heritage Chocolate Makers",
    category: "Cacao",
    description:
      "Artisanal chocolate maker specializing in single-origin chocolate bars and confections.",
    contactPerson: "Sofia Reyes",
    address: "Brgy. Santo Rosario, Tubungan, Iloilo",
    contactNumber: "0925-555-3456",
    productGallery: ["/coffee_and_cacao.jpg"],
    majorProductLines: [],
  },
  {
    id: 27,
    name: "Cacao Craft Philippines",
    category: "Cacao",
    description:
      "Modern cacao processor creating innovative chocolate products with local ingredients.",
    contactPerson: "Diego Santos",
    address: "Brgy. San Pedro, Maasin, Iloilo",
    contactNumber: "0926-555-7890",
    productGallery: ["/coffee_and_cacao.jpg"],
    majorProductLines: [],
  },
  {
    id: 28,
    name: "Iloilo Food Innovators",
    category: "Processed Foods",
    description:
      "Food processing company specializing in traditional Ilonggo delicacies with modern packaging.",
    contactPerson: "Linda Tan",
    address: "Brgy. Poblacion, Pavia, Iloilo",
    contactNumber: "0927-555-1234",
    productGallery: ["/processed_foods.jpg"],
    majorProductLines: [],
  },
  {
    id: 29,
    name: "Kakanin Creations",
    category: "Processed Foods",
    description:
      "Traditional rice cake manufacturer with innovative flavors and packaging.",
    contactPerson: "Rosa Martinez",
    address: "Brgy. San Jose, Oton, Iloilo",
    contactNumber: "0928-555-5678",
    productGallery: ["/processed_foods.jpg"],
    majorProductLines: [],
  },
  {
    id: 30,
    name: "Seafood Delights Processing",
    category: "Processed Foods",
    description:
      "Seafood processing company creating ready-to-eat marine products.",
    contactPerson: "Marco Ramos",
    address: "Brgy. Santo Niño, Villa Arevalo, Iloilo City",
    contactNumber: "0929-555-9012",
    productGallery: ["/processed_foods.jpg"],
    majorProductLines: [],
  },
  {
    id: 31,
    name: "Fruit Valley Preserves",
    category: "Processed Foods",
    description:
      "Manufacturer of fruit preserves, jams, and dried fruit products.",
    contactPerson: "Elena Cruz",
    address: "Brgy. San Miguel, San Miguel, Iloilo",
    contactNumber: "0930-555-3456",
    productGallery: ["/processed_foods.jpg"],
    majorProductLines: [],
  },
  {
    id: 32,
    name: "Native Delicacies Co.",
    category: "Processed Foods",
    description: "Producer of traditional Filipino snacks and delicacies.",
    contactPerson: "Antonio Reyes",
    address: "Brgy. Poblacion, Santa Barbara, Iloilo",
    contactNumber: "0931-555-7890",
    productGallery: ["/processed_foods.jpg"],
    majorProductLines: [],
  },
  {
    id: 33,
    name: "Digital Solutions Hub",
    category: "IT - BPM",
    description:
      "Software development company specializing in web and mobile applications.",
    contactPerson: "James Lee",
    address: "Brgy. Mandurriao, Iloilo City",
    contactNumber: "0932-555-1234",
    productGallery: ["/it-bpm.jpg"],
    majorProductLines: [],
  },
  {
    id: 34,
    name: "Tech Innovators Inc.",
    category: "IT - BPM",
    description:
      "IT consulting firm providing digital transformation solutions.",
    contactPerson: "Patricia Wong",
    address: "Brgy. Molo, Iloilo City",
    contactNumber: "0933-555-5678",
    productGallery: ["/it-bpm.jpg"],
    majorProductLines: [],
  },
  {
    id: 35,
    name: "Cloud Services PH",
    category: "IT - BPM",
    description: "Cloud computing and managed services provider.",
    contactPerson: "Michael Garcia",
    address: "Brgy. La Paz, Iloilo City",
    contactNumber: "0934-555-9012",
    productGallery: ["/it-bpm.jpg"],
    majorProductLines: [],
  },
  {
    id: 36,
    name: "Data Analytics Solutions",
    category: "IT - BPM",
    description: "Data analytics and business intelligence service provider.",
    contactPerson: "Sarah Chen",
    address: "Brgy. Jaro, Iloilo City",
    contactNumber: "0935-555-3456",
    productGallery: ["/it-bpm.jpg"],
    majorProductLines: [],
  },
  {
    id: 37,
    name: "Digital Marketing Experts",
    category: "IT - BPM",
    description: "Digital marketing and social media management company.",
    contactPerson: "John Santos",
    address: "Brgy. Arevalo, Iloilo City",
    contactNumber: "0936-555-7890",
    productGallery: ["/it-bpm.jpg"],
    majorProductLines: [],
  },
  {
    id: 38,
    name: "Hablon Weavers Collective",
    category: "Wearables and Homestyles",
    description:
      "Traditional textile weavers creating modern fashion and home accessories.",
    contactPerson: "Maria Lourdes Santos",
    address: "Brgy. Poblacion, Miagao, Iloilo",
    contactNumber: "0937-555-1234",
    productGallery: ["/weaving.png"],
    majorProductLines: [],
  },
  {
    id: 39,
    name: "Modern Filipiniana",
    category: "Wearables and Homestyles",
    description: "Contemporary Filipino fashion designer and manufacturer.",
    contactPerson: "Isabella Cruz",
    address: "Brgy. Villa Arevalo, Iloilo City",
    contactNumber: "0938-555-5678",
    productGallery: ["/weaving.png"],
    majorProductLines: [],
  },
  {
    id: 40,
    name: "Heritage Home Decor",
    category: "Wearables and Homestyles",
    description:
      "Home decor manufacturer using traditional Filipino materials and designs.",
    contactPerson: "Ramon Torres",
    address: "Brgy. Oton, Iloilo",
    contactNumber: "0939-555-9012",
    productGallery: ["/weaving.png"],
    majorProductLines: [],
  },
  {
    id: 41,
    name: "Artisan Accessories Co.",
    category: "Wearables and Homestyles",
    description:
      "Handcrafted jewelry and accessories maker using local materials.",
    contactPerson: "Clara Reyes",
    address: "Brgy. Molo, Iloilo City",
    contactNumber: "0940-555-3456",
    productGallery: ["/weaving.png"],
    majorProductLines: [],
  },
  {
    id: 42,
    name: "Eco-Fashion Philippines",
    category: "Wearables and Homestyles",
    description:
      "Sustainable fashion brand using eco-friendly materials and processes.",
    contactPerson: "Gabriel Santos",
    address: "Brgy. Jaro, Iloilo City",
    contactNumber: "0941-555-7890",
    productGallery: ["/weaving.png"],
    majorProductLines: [],
  },
  {
    id: 43,
    name: "Coco Fiber Innovation Hub",
    category: "Coconut",
    description:
      "Innovative coconut fiber processing facility producing eco-friendly materials for various industries.",
    contactPerson: "Ricardo Mendoza",
    address: "Brgy. San Jose, San Joaquin, Iloilo",
    contactNumber: "0942-555-1234",
    productGallery: ["/coconut.png"],
    majorProductLines: [],
  },
  {
    id: 44,
    name: "Green Coco Solutions",
    category: "Coconut",
    description:
      "Sustainable coconut processing company specializing in organic coconut products.",
    contactPerson: "Maria Elena Santos",
    address: "Brgy. Poblacion, Guimbal, Iloilo",
    contactNumber: "0943-555-5678",
    productGallery: ["/coconut.png"],
    majorProductLines: [],
  },
  {
    id: 45,
    name: "Pure Coconut Essentials",
    category: "Coconut",
    description:
      "Producer of premium coconut-based personal care and wellness products.",
    contactPerson: "Antonio Reyes",
    address: "Brgy. San Miguel, Tigbauan, Iloilo",
    contactNumber: "0944-555-9012",
    productGallery: ["/coconut.png"],
    majorProductLines: [],
  },
  {
    id: 46,
    name: "Coco Charcoal Enterprise",
    category: "Coconut",
    description:
      "Manufacturer of high-quality coconut shell charcoal and activated carbon products.",
    contactPerson: "Juan dela Cruz",
    address: "Brgy. Santo Niño, Tubungan, Iloilo",
    contactNumber: "0945-555-3456",
    productGallery: ["/coconut.png"],
    majorProductLines: [],
  },
  {
    id: 47,
    name: "Island Coconut Trading",
    category: "Coconut",
    description:
      "Export-oriented coconut trading company focusing on virgin coconut oil and other coconut derivatives.",
    contactPerson: "Carmen Flores",
    address: "Brgy. Poblacion, Miagao, Iloilo",
    contactNumber: "0946-555-7890",
    productGallery: ["/coconut.png"],
    majorProductLines: [],
  },
];

// TODO: Remove this mock data once proper CRUD operations are implemented
export const superAdminMockData = {
  sectors: [
    {
      id: 1,
      name: "Bamboo",
      adminCount: 2,
      msmeCount: 8,
    },
    {
      id: 2,
      name: "Coffee",
      adminCount: 1,
      msmeCount: 5,
    },
    {
      id: 3,
      name: "Cacao",
      adminCount: 2,
      msmeCount: 8,
    },
    {
      id: 4,
      name: "Coconut",
      adminCount: 1,
      msmeCount: 6,
    },
    {
      id: 5,
      name: "Processed Foods",
      adminCount: 1,
      msmeCount: 4,
    },
    {
      id: 6,
      name: "IT - BPM",
      adminCount: 1,
      msmeCount: 3,
    },
    {
      id: 7,
      name: "Wearables and Homestyles",
      adminCount: 1,
      msmeCount: 3,
    },
  ],

  adminSignups: [
    {
      id: 101,
      name: "Robert Chen",
      email: "robert.chen@example.com",
      sector: "Bamboo",
      dateApplied: "2024-03-15",
      status: "pending",
    },
    {
      id: 102,
      name: "Maria Garcia",
      email: "maria.garcia@example.com",
      sector: "Coconut",
      dateApplied: "2024-03-16",
      status: "pending",
    },
    {
      id: 103,
      name: "David Kim",
      email: "david.kim@example.com",
      sector: "IT - BPM",
      dateApplied: "2024-03-17",
      status: "pending",
    },
  ],

  admins: [
    {
      id: 1,
      name: "John Doe",
      email: "john.doe@example.com",
      sector: "Bamboo",
      dateAdded: "2024-01-15",
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "jane.smith@example.com",
      sector: "Coffee & Cacao",
      dateAdded: "2024-01-20",
    },
    {
      id: 3,
      name: "Mike Johnson",
      email: "mike.j@example.com",
      sector: "Coconut",
      dateAdded: "2024-02-01",
    },
    {
      id: 4,
      name: "Sarah Wilson",
      email: "sarah.w@example.com",
      sector: "Processed Foods",
      dateAdded: "2024-02-15",
    },
  ],

  // Convert msmeLines to the format needed for superadmin
  msmes: msmeLines.map((msme) => ({
    id: msme.id,
    name: msme.name,
    email: `contact@${msme.name.toLowerCase().replace(/\s+/g, "")}.com`,
    businessType: "Manufacturing",
    sector: msme.category,
    address: msme.address,
    contactNumber: msme.contactNumber,
    contactPerson: msme.contactPerson,
    registrationDate: new Date(
      2023,
      Math.floor(Math.random() * 12),
      Math.floor(Math.random() * 28) + 1,
    )
      .toISOString()
      .split("T")[0],
    status: "Active",
  })),
};
